layout_spectrum: 0.5681003
color:
  saturation: 0.6935484
  lightness: 0.4050179
  brandStrength: 0.5197133
  brandColors:
    - '#0E0D0D'
    - '#885441'
    - '#C5886E'
    - '#FFFFFB'
    - '#FFFBA3'
  rhythmicContrast: 0.453405
typography_spectrum: 0.6792115
name: 'Marcus Kim '
